### ISSUE TITLE
License key error with 1.1

### ISSUE THREAD

**Issue by MJMODZZ-V3** [mazkdevf/KeyAuth-JS-Example#19]
Whenever you try to login with a license key, it tells "invalid license"
Even when its valid so it doesnt really work anymore

**Comment by mazkdevf** [comment]
Interesting.

**Comment by mazkdevf** [comment]
![image](https://github.com/mazkdevf/KeyAuth-JS-Example/assets/79049205/3e753180-8dd7-42fc-ab91-8712310ad4f5)

Tested and works fine 18.07.2023 22:30 Finnish UTC +3 Time
